build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7

init:
  - "ECHO %PYTHON_VERSION%"

install:
  - pip install pytest
  - pip install git+https://github.com/tomaszkurgan/pytesting@master

test_script:
  - "SET PYTHONPATH=%CD%/source;%PYTHONPATH%"
  - "ECHO %PYTHONPATH%"
  - pytest -s
